default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: brickyard_development
  username: <%= ENV['BRICKYARD_DB_USER'] %>
  password: <%= ENV['BRICKYARD_DB_PASSWD'] %>

test:
  <<: *default
  database: brickyard_test
  username: <%= ENV['BRICKYARD_DB_USER'] %>
  password: <%= ENV['BRICKYARD_DB_PASSWD'] %>

production:
  <<: *default
  database: brickyard_production
  username: <%= ENV['BRICKYARD_DB_USER'] %>
  password: <%= ENV['BRICKYARD_DB_PASSWD'] %>
